steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/kalopathor/hawkeye:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/kalopathor/hawkeye:latest']
images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/kalopathor/hawkeye:latest'
timeout: '1200s'
