import {NextResponse} from 'next/server';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';

// Static freshness.json generated by gen_freshness.py on the OVH server.
// Served as a static file from public/data/freshness.json.
// This API route exists as a fallback and to set correct cache headers.

export const revalidate = 60;

export async function GET() {
  try {
    // Try reading from public/data/freshness.json (bundled at build time)
    const staticPath = join(process.cwd(), 'public', 'data', 'freshness.json');
    const raw = await readFile(staticPath, 'utf8');
    const data = JSON.parse(raw);

    return NextResponse.json(data, {
      headers: {
        'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=120',
      },
    });
  } catch {
    // If file doesn't exist, return a minimal honest response
    return NextResponse.json(
      {
        mode: 'seeded',
        server_time: new Date().toISOString(),
        error: 'freshness.json not found — gen_freshness.py may not have run',
        layers: {
          ffwc_gauges: {basis: 'seeded', last_success: null, status: 'failed', stale_after_s: 3600},
          sar_detection: {basis: 'live', last_pass: null, next_pass: null, next_pass_source: 'satmarg', region: 'national', status: 'failed'},
          forecast_glofas: {basis: 'seeded', run_ts: null, status: 'failed'},
          forecast_openmeteo: {basis: 'seeded', run_ts: null, status: 'failed'},
          shelters: {basis: 'static', version: '0.1.0', provenance: 'proxy', status: 'failed'},
          model: {basis: 'static', version: 'd3v4.2', frozen: true},
        },
      },
      {
        headers: {
          'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=120',
        },
      }
    );
  }
}
